apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: airbyte/seed
    newTag: dev
  - name: airbyte/db
    newTag: dev
  - name: airbyte/scheduler
    newTag: dev
  - name: airbyte/server
    newTag: dev
  - name: airbyte/webapp
    newTag: dev

resources:
  - db.yaml
  - scheduler.yaml
  - scheduler-service-account.yaml
  - server.yaml
  - volume-configs.yaml
  - volume-db.yaml
  - volume-workspace.yaml
  - webapp.yaml

# configMapGenerator:
#   - name: airbyte-env
#     files: 
#     - airbyte-env


configMapGenerator:
  - name: airbyte-env
    env: .env
