apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: airbyte/seed
    newTag: 0.16.1-alpha
  - name: airbyte/db
    newTag: 0.16.1-alpha
  - name: airbyte/scheduler
    newTag: 0.16.1-alpha
  - name: airbyte/server
    newTag: 0.16.1-alpha
  - name: airbyte/webapp
    newTag: 0.16.1-alpha

resources:
  - db.yaml
  - scheduler.yaml
  - scheduler-service-account.yaml
  - server.yaml
  - volume-configs.yaml
  - volume-db.yaml
  - volume-workspace.yaml
  - webapp.yaml
  - ingress.yaml

configMapGenerator:
  - name: airbyte-env
    files: 
    - airbyte-env
    
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated