apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbyte-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      airbyte: scheduler
  template:
    metadata:
      labels:
        airbyte: scheduler
    spec:
      serviceAccountName: airbyte-admin
      automountServiceAccountToken: true
      containers:
        - name: airbyte-scheduler-container
          image: airbyte/scheduler
          env:
            - name: AIRBYTE_VERSION
              value: 0.16.1-alpha
            - name: CONFIG_ROOT
              value: /configs
            - name: DATABASE_PASSWORD
              value: docker
            - name: DATABASE_URL
              value: jdbc:postgresql://airbyte-db-svc:5432/airbyte
            - name: DATABASE_USER
              value: docker
            - name: TRACKING_STRATEGY
              value: segment
            - name: WAIT_BEFORE_HOSTS
              value: "5"
            - name: WAIT_HOSTS
              value: airbyte-db-svc:5432
            - name: WAIT_HOSTS_TIMEOUT
              value: "45"
            - name: WORKSPACE_DOCKER_MOUNT
              value: workspace
            - name: WORKSPACE_ROOT
              value: /workspace
            - name: WORKER_ENVIRONMENT
              value: kubernetes
            - name: LOCAL_ROOT
              value: /local_undefined
          ports:
            - containerPort: 8001
          volumeMounts:
            - name: airbyte-volume-configs
              mountPath: /configs
            - name: airbyte-volume-workspace
              mountPath: /workspace
      initContainers:
        - name: airbyte-seed
          image: airbyte/seed
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "mkdir -p /configs/config && yes n | cp -r -i /app/seed/config /configs",
            ]
          volumeMounts:
            - name: airbyte-volume-configs
              mountPath: /configs
            - name: airbyte-volume-workspace
              mountPath: /workspace
      volumes:
        - name: airbyte-volume-workspace
          persistentVolumeClaim:
            claimName: airbyte-volume-workspace
        - name: airbyte-volume-configs
          persistentVolumeClaim:
            claimName: airbyte-volume-configs
