apiVersion: v1
kind: Service
metadata:
  name: airbyte-webapp-svc
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
  selector:
    airbyte: webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbyte-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      airbyte: webapp
  template:
    metadata:
      labels:
        airbyte: webapp
    spec:
      containers:
        - name: airbyte-webapp-container
          image: airbyte/webapp
          env:
            - name: AIRBYTE_VERSION
              value: 0.16.1-alpha
            - name: API_URL
              value: 
            - name: TRACKING_STRATEGY
              value: segment
            - name: PAPERCUPS_STORYTIME
              value: enabled
            - name: IS_DEMO
              value: "false"
          ports:
            - containerPort: 80
