apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: redis
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: '10.7.13'
    chart: redis
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: global.storageClass
          value: 'gp2retain'
        - name: cluster.enabled
          value: 'true'
        - name: cluster.slaveCount
          value: '3'
        - name: usePassword
          value: 'false'
        - name: sentinel.enabled
          value: 'false'
      version: v3
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - Validate=true