nameOverride: ""

global:
  imagePullSecrets: []
  imagePullPolicy: IfNotPresent
  # storageClass: myStorageClass

webapp:
  image:
    repository: blotout/airbyte-webapp
    tag: api-d262d986903bca1c7092bf7f697d7f2146c4f54e
  replicas: 1
  service:
    name: airbyte-webapp-svc
    containerPort: 80

server:
  image:
    repository: blotout/airbyte-server
    tag: api-d262d986903bca1c7092bf7f697d7f2146c4f54e

scheduler:
  image:
    repository: blotout/airbyte-scheduler
    tag: api-d262d986903bca1c7092bf7f697d7f2146c4f54e

seed:
  image:
    repository: blotout/airbyte-seed
    tag: api-d262d986903bca1c7092bf7f697d7f2146c4f54e

temporal:
  image:
    repository: temporalio/auto-setup
    tag: 1.7.0
  replicas: 1

# volumeconfigs:
#   disksize: "5"
# volumeworkspace:
#   disksize: "5"

ingress:
  enabled: "true"
  annotations: {}
  labels: {}
  hosts:
    - airbyte-stage.blotout.io
  paths:
    - /
